[build]
builder = "DOCKERFILE"
dockerfilePath = "ops/Dockerfile"

[deploy]
startCommand = "node solution/website/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
